#!/usr/bin/bash

# waybar
$HOME/Scripts/waybar_top.sh &
$HOME/Scripts/waybar_bottom.sh &

# terminal, mako and bg
foot --server &
mako &
swaybg -i $HOME/Pictures/bg/bolle_blu.png -m center &

# wayalnd
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

gsettings set org.gnome.desktop.interface gtk-theme Adwaita &
gsettings set org.gnome.desktop.interface icon-theme Haiku &
gsettings set org.gnome.desktop.interface cursor-theme Adwaita &
gsettings set org.gnome.desktop.interface font-name 'Cantarell Regular 12' &
gsettings set org.gnome.desktop.interface text-scaling-factor 1 &
